Received: from X32.Tymnet by D35.Tymnet; Fri, 6 Jan 89 13:46:54 PST
Return-path: <OSMAN@D35> 
From: Osman Guven <OSMAN@D35> 
Date: Fri, 6 Jan 89 13:44:06 PST 
To: Carl Baltrunas <Carl@D35> 
Subject: Wayne Bartlett .. 

He wants to set up a meeting with you some time next week.

-Osman-

Received: from EMSTXS.Ontyme.Tymnet by D35.Tymnet; Sat, 7 Jan 89 14:01:33 PST
Received: from F74.Tymnet by EMSTUMS.Ontyme.Tymnet; Fri, 6 Jan 89 14:09:50 PST
Received: from D35.Tymnet by F74.Tymnet; Fri, 6 Jan 89 14:09:27 PST
Received: from EMSFSC.Ontyme.Tymnet by D35.Tymnet; Fri, 6 Jan 89 14:09:08 PST
Return-path: <NSC.C/HOEKE@EMSFSC.Ontyme.Tymnet> 
From: NSC.C/HOEKE@EMSFSC.Ontyme.Tymnet 
Date: 06 JAN 89 09:38:47 
To: FSC.C/BALTRUNAS@EMSFSC.Ontyme.Tymnet 
Message-id: M13218@Ontyme.Tymnet 
Subject: IMPORTANT LICENSE MESSAGE 

***IMPORTANT NOTE***

     THIS IS A REMINDER.  PLEASE HAVE ALL EMPLOYEES THAT HAVE A LICENSE NAME
     RUN AND FILL OUT THE EXEC MENTIONED BELOW.  THANK YOU FOR YOUR EFFORT.

     IF THERE ARE ANY QUESTIONS, PLEASE REFER THEM TO CYNTHIA HOEKE.  SHE
     CAN BE REACHED EITHER AT 408/922-7086 OR BY ONTYME NSC.INTERNAL

**********************************************************************
                                  T Y M N E T 

                   MCDONNELL DOUGLAS NETWORK SYSTEMS COMPANY

                              M E M O R A N D U M

DATE>      05 DEC 88  13:31

TO>        All Setops License Managers

COPIES>    Wayne Bartlett
           Director Data Security

FROM>      Vida Stafford
           Supervisor Tymnet Validations


SUBJECT>   License Information


-----------------------------------------------------------------------



We are sending the following memo to you as managers in the license tree.
Please ensure that all users under your management comply.

The Validations Department is in the process of updating our current infor-
mation on employees who have status names.

We appreciate your cooperation, and we hope you understand that this is a
necessary step to improve the security of our Network. Basically, it will 
provide accountability, and will give us immediate access to the person that
owns the status name.

This security enhancement is particularly significant in light of the recent
unfortunate publicity about Tymnet Security practices. Call me (X7316) if
you'd like a copy of the article.



We are requesting that anyone who currently has a status name, run our exec
** license.req. This exec will prompt you for the information that we need
in order to update our files. It will be available on or before 12-12-88.

People who have not provided the required information by January 13,1989,
will be barred from setting license after that date.
                                                                Page  2
From: JMS@D35.Tymnet 
Date: Tue, 10 Jan 89 11:36:43 PST 
To: carl 
Subject: "Do you have the new TUMS aliases"... 

Do you have the new TUMS aliases for BARTLETW@B39, DERNST@B39, and
ANEWMAN@B39?  I have located WRS@BUFFALO from his MAIL.FWD.
From: Carl A Baltrunas <Carl@F35.Tymnet> 
Date: Wed, 11 Jan 89 1:32:56 PST 
To: Joe Smith <JMS> 
Subject: New aliases 

No, that is why I was asking about B39, I figured Bill was WRS@BUFFALO
but don't have anyone elses address yet.  Will probably give Dennis or
Adele a call.

DENCOFF is moved to the public net, I think 33.. not sure about anyone
else.  I'll ask Wayne on thursday for their new address.

/Carl
From: Carl A Baltrunas <Carl@F35.Tymnet> 
Date: Wed, 11 Jan 89 13:04:33 PST 
To: Debbie Shutt <MDCIS.D/Shutt@Ontyme.Tymnet> 
Subject: TYMNET checking out the engine 

Debbie,
  An additional thought...  Ken mentioned that they were dialing into the
engine that you get using the local number (314) {I presume} 731-8002.  I
suggest that TYMNET also check out that node if at all possible.

  Thanks.

/Carl
From: Carl A Baltrunas <Carl@F35.Tymnet> 
Date: Wed, 11 Jan 89 13:17:04 PST 
To: Debbie Shutt <MDCIS.D/Shutt@Ontyme.Tymnet> 
Subject: TYMNET problem? 

Debbie,
  Both Ken and Earl are having the problem that things don't work at
1200 baud any more.  They used to work.

  They are able to get things to work if they drop the line speed down
to 300 baud.

  I feel that this is significant, and may help TYMNET isolate the problem.
I will pursue the issue here with people I know in TYMNET as far as known
problems with new (if any) releases of network code.

/Carl
 PS.  Please pass this info on to whomever comes in to look at the engines.
Received: from F74.Tymnet by D35.Tymnet; Thu, 12 Jan 89 9:16:22 PST
Return-path: <DANIELSR@F74.Tymnet> 
From: DANIELSR@F74.Tymnet 
Date: Thu, 12 Jan 89 9:15:28 PST 
To: CARL 
Subject: "Carl; All of F29's disk packs"... 


Carl;

All of F29's disk packs are on line.  Call Operations on what you want
them to do.

Thanks Rick
Received: from F74.Tymnet by D35.Tymnet; Thu, 12 Jan 89 11:51:54 PST
Return-path: <DANIELSR@F74.Tymnet> 
From: DANIELSR@F74.Tymnet 
Date: Thu, 12 Jan 89 11:50:08 PST 
To: CARL 
Subject: "Carl; F29's disk packs are on"... 


Carl;

F29's disk packs are on B39's old disk drives.  Brought system up
by change system to 39 in MANUAL mode, but cannot log
in on OPER Terminal.

You may have to come to the Center to do what you have
to do with this system.

Thanks Rick
Received: from F74.Tymnet by D35.Tymnet; Fri, 13 Jan 89 13:44:47 PST
Return-path: <JMS@F74.TYMNET> 
From: Joe Smith <JMS@F74.TYMNET> 
Date: Fri, 13 Jan 89 13:15:13 PST 
To: Monitor Group <JMS>, Carl, Osman, FSC.J/HEALY@ONTYME 
Cc: FletcherC, ngot@trw, nowellr@trw, JMS@TRW 
Subject: X14 is running on an 11/23. 

Node 6760, the base for our 2020 host X14, has been upgraded from an LSI-11/03
to an 11/23.  I didn't even have to change SV6760.BND - it loaded the old code
with no problems.  The node has 2 lines running at 9600 baud, the line to
neighbor node 5561 is active with no errors.

The line to neighbor node 5416 is suspended because that node has no XLINKs
and is not configured to talk to node 6760.  We cannot really exersize this
configuration unless TYMNET changes the TYM file for node 5416 and adds an
additional TIILNK for 6760.

		/Joe
Received: from D34.Tymnet by D35.Tymnet; Mon, 16 Jan 89 7:18:02 PST
Return-path: <Carl@D35.Tymnet> 
From: Carl A Baltrunas <Carl@D35.Tymnet> 
Date: Mon, 16 Jan 89 9:14:15 CST 
To: Craig Fletcher <fletcherc@D35.Tymnet> 
Subject: Schedule 

I will be in late today.

  My cough has gotten alittle better, but not enough for me to work
without additional sleep.  I have completed the bulk of the work for
solving all the problems with the new SETOP.

  I still want them to beta-test/qa the product before I put it into
production.  It needs soe "stress-testing".

  Please have Karin call me at home when she returns from lunch or
around 1:30pm, whichever is later.  I expect to be in around 2:30pm.

/Carl
Received: from F33.Tymnet by D35.Tymnet; Mon, 16 Jan 89 11:46:58 PST
Return-path: <Postmaster@F33.Tymnet> 
From: Postmaster@F33.Tymnet 
Date: Mon, 16 Jan 89 10:12:35 PST 
To: Carl A Baltrunas <Carl> 
Subject: Returned MAIL 

The following message was not delivered because:
No router table entry for "39.Q".



----------
RCPT To: <BARTLETW@B39.Tymnet> 
From: Carl A Baltrunas <Carl> 
Date: Mon, 16 Jan 89 6:38:29 PST 
To: Wayne D Bartlett <BARTLETW@B39.Tymnet> 
Bcc: CARL@F33.Tymnet 
Subject: SETOP roll over 

Wayne & Vida & Cynthia,

As I said I would, I have rolled the opername data base into the new system.

However, there is still some amount of testing, and a small matter of making
sure that the license kept on the system password file is not lost.

I also have made all of the programming changes as per our conversation on
Thursday.  As per that meeting, I have noot been felling as well as I would
like and have not done what I consider sufficient testing of the new features
added in the last week.

I will call you (Cynthia) sometime this afternoon to discuss having you do
some "stress-testing" to make sure nothing will break when we make this live
for all users on the system.

PS. Since I am developing on system 33, that is where the current TEST system
resides.  I will move it to 74 today, so I may fix anything that you find
without breaking anything else.

PPS.  Wayne, I would prefer that Cynthia do some amount of double-entering
      using one of these test systems.  I will coordinate with her when and
      where she can start.

PPPS.  Wayne, I do not have the correct ONTYME address for either Cynthia or
       Vida.  COuld you please put a copy of this memo on their desks.

Thanks a lot.

/Carl
Received: from F74.Tymnet by D35.Tymnet; Tue, 17 Jan 89 14:10:41 PST
Received: from D35.Tymnet by F74.Tymnet; Tue, 17 Jan 89 14:04:34 PST
Received: from EMSTXS.Ontyme.Tymnet by D35.Tymnet; Tue, 17 Jan 89 14:01:17 PST
Received: from F74.Tymnet by EMSNSC.Ontyme.Tymnet; Mon, 16 Jan 89 23:01:15 PST
Received: from tymix.Tymnet.COM.Tymnet.COM by F74.Tymnet; Mon, 16 Jan 89
	23:00:57 PST
Received: by tymix.Tymnet.COM.Tymnet.COM (5.51/4.7) id AA27212; Mon, 16 Jan 89
	22:08:16 PST
Received: by gleep.Tymnet.com (3.2/SMI-3.2) id AA04530; Mon, 16 Jan 89 22:08:08
	PST
Return-path: <JMS@F74.TYMNET> 
From: julies@gleep (Julie Stier) 
Date: Mon, 16 Jan 89 22:08:08 PST 
To: TXS.J/SMITH@EMSNSC.Ontyme.Tymnet.com 
Cc: TXS.C/BATRUNAS@EMSNSC.Ontyme.Tymnet.com,
	TXS.O/GUVEN@EMSNSC.Ontyme.Tymnet.com 
Message-id: <8901170608.AA04530@gleep.Tymnet.com> 
Subject: Sun validations 
Resent-from: Joe Smith <JMS@F74.TYMNET> 
Resent-date: Tue, 17 Jan 89 14:10:28 PST 
Resent-to: carl 


Joe,

The 3 validations requested for Carl, Osman and yourself have been completed
as follows:

usernames -
        carl
        osman
        jms

home - /usr/opus3/misc

default password - change me

Let me know if there are any problems with this.

julie
Received: from F74.Tymnet by D35.Tymnet; Tue, 17 Jan 89 14:15:32 PST
Return-path: <JMS@F74.TYMNET> 
From: Joe Smith <JMS@F74.TYMNET> 
Date: Tue, 17 Jan 89 14:10:40 PST 
To: <julies@gleep> 
Cc: OSMAN@D35, CARL@D35 
Subject: Re: Sun validations 
In-reply-to: <8901170608.AA04530@gleep.Tymnet.com> of Mon, 16 Jan 89 22:08:08
	PST

Thank you.  I have forwarded the message to TXS.C/BALTRUNAS (no such user as
TXS.C/BATRUNAS).  Please add the "L" to Carl's last name in /etc/passwd.

		/Joe

Received: from F74.Tymnet by D35.Tymnet; Tue, 17 Jan 89 15:50:28 PST
Received: from TRW.Tymnet by F74.Tymnet; Tue, 17 Jan 89 15:50:09 PST
Return-path: <NGOT@TRW.Tymnet> 
From: NGOT@TRW.Tymnet 
Date: Tue, 17 Jan 89 15:43:24 PST 
To: JMS, CARL, NINKEJ, NGOT, WRFS, NOWELLR 
Subject: "HI EVERYONE, THE DEC2020 SYSTEM"... 

HI EVERYONE,

   THE DEC2020 SYSTEM WENT DOWN TODAY WITH AN ERROR MESSAGE AS FOLLOWING:

   ?HALT STOPCODE "MAPAL1" AT 17-JAN-1989 15:10:43
   S33TRW, HARDWARE TW, KS-4097 , BASE 2020, S33-P035/D08, 10-06-88, M02541
   FRAME 12 TTY23 [0,0]([10,65432]) AT S33TRW
   RUNNING (SYS)LOGINN[1,4]
    UUO IS 047500,,777711 AT EXEC PC 042454
   MUU0 IS 064140,,000001 AT USER PC 402207
   RELOAD MONITOR

   THE CRASH DUMP IS LOCATED UNDER (SYS)CRA###.SAV.

   PLEASE TAKE A LOOK INTO THAT AND LET JON NINKE OR TINA NGO WHERE ARE
WE STAND ON THAT.  THANK YOU....

                                   TINA NGO.

Received: from F74.Tymnet by D35.Tymnet; Tue, 17 Jan 89 18:51:27 PST
Received: from TRW.Tymnet by F74.Tymnet; Tue, 17 Jan 89 18:51:16 PST
Return-path: <JMS@TRW.Tymnet> 
From: JMS@TRW.Tymnet 
Date: Tue, 17 Jan 89 18:44:14 PST 
To: NGOT@TRW.Tymnet 
Cc: CARL, NINKEJ, NGOT, WRFS, NOWELLR, osman 
Subject: Re: MAPAL1 crash 
In-reply-to: your message of Tue, 17 Jan 89 15:43:24 PST

The MAPAL1 stopcode in CRA001.SAV is a result of the Monitor getting confused
as to which pages were available.  It is a software problem that was cleared
up by running DSKCLN.  Please let us know if it occurs again.

		/Joe
Received: from F33.Tymnet by D35.Tymnet; Tue, 17 Jan 89 19:12:48 PST
Return-path: <JMS@F74.TYMNET> 
From: Joe Smith <JMS@F74.TYMNET> 
Date: Tue, 17 Jan 89 18:52:31 PST 
To: Monitor Group <JMS>, Carl, Osman 
Cc: FletcherC 
Subject: Analysis of TRW's MAPAL1 crash. 

LOGINN was running and did an INBUF uuo which caused the low-seg to be
expanded to handle the input buffers.  The kernel did a VCREAT uuo, asking
for 2 writeable pages starting at user virtual page 2.  One page was
allocated and a second one contiguous to the first was requested.  The
MAPAL1 occured when PCBIO was asked to read a bogus SAT page for SWAMP.

Something went wrong in GETPAG while allocating the first page.  It returned
200004,,467125 which is an error; the highest page on an RP06 is 227161 octal.
The bogus disk address was found in ac M and in the UPT and UPT+UPTLMA.
When GETPAG was called the second time, is took the bogus disk address,
calculated the address where the STT would be if the disk had that many
pages, and read random garbage as an STT entry.  It read this garbage as
if it were a retreival pointer and passed it on to PCBIO.  The MAPAL1 crash
is a result of RBREAL not being set on this garbage pointer.

There was no bounds checking in the GETSTT routine in SWAMP.  I put in a
check against UNIPAG.  This will fix this particular MAPAL1 scenario but
until the problem in GETPAG is found, bad data can still get put into the
UPT.  That will cause a PAGPOR (page out of range) stopcode when the page
is faulted in.

I have not checked the logic in GETPAG to find out why it could return a
bogus value.  It may have been that the very last SAT page of the last
unit was in-core and completely full (and the routine fell off the end
of DSKB).			/Joe
Received: from F74.Tymnet by D35.Tymnet; Wed, 18 Jan 89 1:02:28 PST
Return-path: <Carl@D35.Tymnet> 
From: Carl A Baltrunas <Carl@D35.Tymnet> 
Date: Wed, 18 Jan 89 0:54:17 PST 
To: Joe Smith <JMS@D35.Tymnet> 
Subject: re: TOPS-10 FIle being modified (3) 

Joe,
  I setup FACT.CTL to submit FCTLOG.CTL for /after:+0:05 just before it
finishes.  FCTLOG.CTL simpley renames FACT?.LOG to FACTn.LOG where n is
increased each time it runs, making FACT.LOG ==> FACT1.LOG.

  Well, normally I'd expect this to work... but it doesn't.  It gets the
file being modified error.

  Background:  I foolishly [?] tried having this rename occur while inside
FACT.CTL and (of course, received FIle being modified (3) as the error).
This was earlier this afternoon.  I created FOO.CTL and submitted it as:
  SUBMIT FACT=FOO.CTL/...     then
  SUBMIT FACT/TIME:10:00/UNIQUE:0/AFTER:3:00   to run tonight...

Anyway, I just logged in and FCTLOG ran 5 minutes after FACT completed and
still got the File being modified error.  I tried it by hand, nearly an hour
after BATCON finished running FACT and I got the File being modified error.

Who has the file open?  Why?  Is this a bug in 7.01?

/Carl
Received: from F74.Tymnet by D35.Tymnet; Wed, 18 Jan 89 1:07:25 PST
Return-path: <Carl@D35.Tymnet> 
From: Carl A Baltrunas <Carl@D35.Tymnet> 
Date: Wed, 18 Jan 89 1:04:01 PST 
To: Joe Smith <JMS@D35.Tymnet> 
Subject: Re: FIle being modified 

Please take a look at FACT.LOG and FCTLOG.LOG DSKB:[1,2] on KL#1300
I'd ultimately like to have the FACT.LOG for each day printed and then
renamed to FACTn.LOG and keep 7 copies.  I want the copies on-line for
me to check, otherwise I'd just have BATCON delete it after printing.
I don't want to print an ever-increasing FACT.LOG every day, but I do
want to print it every day for their benefit!

/Carl
From: Carl A Baltrunas <Carl@F35.Tymnet> 
Date: Wed, 18 Jan 89 1:08:05 PST 
To: Joe Smith <JMS> 
Subject: re: OPUS? how to get there? 


From: Carl A Baltrunas <Carl@F35.Tymnet> 
Date: Wed, 18 Jan 89 5:56:38 PST 
To: Joe Smith <JMS> 
Subject: opus 

Never mind... BUBBNET/OPUS ...  That was easy to get accounts on OPUS,
what have you been up to?

/Carl
Received: from F74.Tymnet by D35.Tymnet; Wed, 18 Jan 89 11:21:33 PST
Return-path: <DANIELSR@F74.Tymnet> 
From: DANIELSR@F74.Tymnet 
Date: Wed, 18 Jan 89 11:20:36 PST 
To: osman, jms, carl, osman, danielsr 
Subject: "When are we going to get together"... 

When are we going to get together so you can teach
me some of the TYMCOM-10'S SOFTWARE FIXES?

THANKS RICK
Received: from F74.Tymnet by D35.Tymnet; Wed, 18 Jan 89 11:58:45 PST
Return-path: <JMS@F74.TYMNET> 
From: Joe Smith <JMS@F74.TYMNET> 
Date: Wed, 18 Jan 89 11:54:52 PST 
To: <Carl@D35.Tymnet> 
Subject: re: TOPS-10 FIle being modified (3) 
In-reply-to: your message of Wed, 18 Jan 89 0:54:17 PST

Maybe BATCON does not close the LOG file until another job is scheduled
for that stream.  I usually use the following:
	.DELETE FACT3.LOG
	.RENAME FACT3.LOG=FACT2.LOG
	.RENAME FACT2.LOG=FACT1.LOG
	.COPY FACT1.LOG=FACT.LOG
	.KJOB
Received: from F74.Tymnet by D35.Tymnet; Wed, 18 Jan 89 11:59:30 PST
Return-path: <JMS@F74.TYMNET> 
From: Joe Smith <JMS@F74.TYMNET> 
Date: Wed, 18 Jan 89 11:58:48 PST 
To: <Carl@F35.Tymnet> 
Subject: re: OPUS? how to get there? 
In-reply-to: your message of Wed, 18 Jan 89 1:08:05 PST

	please log in: BUBB
	please log in: OPUS
	login: carl
Received: from F74.Tymnet by D35.Tymnet; Wed, 18 Jan 89 15:57:21 PST
Return-path: <TYMRES5@F74.Tymnet> 
From: TYMRES5@F74.Tymnet 
Date: Wed, 18 Jan 89 15:56:09 PST 
To: CARL 
Subject: "CARL, I AM SENDING YOU MAIL BECAUSE"... 

CARL,  I AM SENDING YOU MAIL BECAUSE WHEN TRYING TO PULL UP A NEW COPY
OF THE RO FHTELOG
Received: from EMSTXS.Ontyme.Tymnet by D35.Tymnet; Fri, 20 Jan 89 14:01:53 PST
Received: from F74.Tymnet by EMSTUMS.Ontyme.Tymnet; Thu, 19 Jan 89 14:11:24 PST
Received: from D35.Tymnet by F74.Tymnet; Thu, 19 Jan 89 14:05:31 PST
Received: from EMSFSC.Ontyme.Tymnet by D35.Tymnet; Thu, 19 Jan 89 14:05:06 PST
Return-path: <MDCIS.D/SHUTT@EMSFSC.Ontyme.Tymnet> 
From: MDCIS.D/SHUTT@EMSFSC.Ontyme.Tymnet 
Date: 19 JAN 89 09:26:34 
To: FSC.C/BALTRUNAS@EMSFSC.Ontyme.Tymnet 
Message-id: J92986@Ontyme.Tymnet 
Subject: Trip to CA 
TriptoCalifornia: 

                        MCDONNELL DOUGLAS
                   COMMUNICATIONS INDUSTRY SYSTEMS COMPANY

DATE>      19 JAN 89  11:22

TO>        Carl Baltrunas

COPIES>    

FROM>      Debbie Shutt


SUBJECT>   Trip to California


-----------------------------------------------------------------------


Carl, it looks as though Jim O'Connel will not be coming with me to
San Jose.  How does the week of February 6th look for you.  I was
thinking about flying out on the 8th, spending the day with you on the
9th and coming home on the 10th.  Let me know if you think we need more
time or if this is not good for you.  Also can you recommend a hotel
that is close.

Thanks,
Debbie
Received: from EMSTXS.Ontyme.Tymnet by D35.Tymnet; Fri, 20 Jan 89 14:02:01 PST
Received: from F74.Tymnet by EMSTUMS.Ontyme.Tymnet; Thu, 19 Jan 89 14:13:55 PST
Received: from D35.Tymnet by F74.Tymnet; Thu, 19 Jan 89 14:05:36 PST
Received: from EMSFSC.Ontyme.Tymnet by D35.Tymnet; Thu, 19 Jan 89 14:05:13 PST
Return-path: <MDCIS.D/SHUTT@EMSFSC.Ontyme.Tymnet> 
From: MDCIS.D/SHUTT@EMSFSC.Ontyme.Tymnet 
Date: 19 JAN 89 12:09:07 
To: FSC.C/BALTRUNAS@EMSFSC.Ontyme.Tymnet 
Message-id: J93068@Ontyme.Tymnet 
Subject: Cancel EASOP Usernames 
CancelEASOPUsernames: 

                             MCDONNELL DOUGLAS
                   COMMUNICATIONS INDUSTRY SYSTEMS COMPANY

DATE>      19 JAN 89  14:02

TO>        Carl Baltrunas

COPIES>    

FROM>      Debbie Shutt


SUBJECT>   Cancel EASOP Usernames


-----------------------------------------------------------------------


Carl, please cancel the following EASOP usernames from the KL-10 system.
I received these from Ted Atkinson today.  When I come out, you can
show me how to do this.

NE2311TC   NE2541TC

If you have any questions, please call.  Thanks for your help...


Debbie
Received: from D34.Tymnet by D35.Tymnet; Sat, 21 Jan 89 22:31:17 PST
Return-path: <Carl@D35.Tymnet> 
From: Carl A Baltrunas <Carl@D35.Tymnet> 
Date: Sun, 22 Jan 89 0:27:15 CST 
To: requestop 
Subject: Change to name of field 

Vida & Cynthia,

  As per the confusion that you had with "License" and "Privilege" and
"Capability" that I has in the documentation and the testing that Cynthia
had done on system 74, I have changed the name of one of the fields:

  Instead of calling it "License" it is now called "Capability" and is
both listed as "Capability" and the new prompt says "Capability (MG LG):".

  I showed the documentation to the members of my group and they had the
same questions.  Thus, I expect everyone will have the same questions and
so it has been changed...

/Carl
Received: from F33.Tymnet by D35.Tymnet; Sun, 22 Jan 89 4:56:38 PST
Return-path: <PERPOPER@F33.Tymnet> 
Reply-to: SUBMIT 
From: F33 Job Processor 
Sender: PERPOPER@F33.Tymnet 
Date: Sun, 22 Jan 89 12:56:26 UT 
To: SYS 
Subject: Req #51424 DSK:(SYS)REDSAT.SAV Abort-Time (0) 

; Processed:  Req #51424  Running DSK:(SYS)REDSAT.SAV
; Scheduled:  10-Jan-89 11:45:49
; Actual run: 22-Jan-89 03:56:09
;
; Options:  Mail:Error Unique:Job
; Limits:  Time 60  TRUs 0
; Flags:   Run  Detach  Logout
; Status:  Abort-Time (0)  at  22-Jan-89 04:56:25

Received: from F33.Tymnet by D35.Tymnet; Sun, 22 Jan 89 6:37:15 PST
Return-path: <PERPOPER@F33.Tymnet> 
Reply-to: SUBMIT 
From: F33 Job Processor 
Sender: PERPOPER@F33.Tymnet 
Date: Sun, 22 Jan 89 14:37:04 UT 
To: SYS 
Subject: Req #51424 DSK:(SYS)REDSAT.SAV Abort-Time (0) 

; Processed:  Req #51424  Running DSK:(SYS)REDSAT.SAV
; Scheduled:  10-Jan-89 11:45:49
; Actual run: 22-Jan-89 03:56:09
;
; Options:  Mail:Error Unique:Job
; Limits:  Time 60  TRUs 0
; Flags:   Run  Detach  Logout
; Status:  Abort-Time (0)  at  22-Jan-89 06:37:04

Received: from F33.Tymnet by D35.Tymnet; Mon, 23 Jan 89 0:25:38 PST
Return-path: <JMS@F74.TYMNET> 
From: Joe Smith <JMS@F74.TYMNET> 
Date: Mon, 23 Jan 89 0:13:27 PST 
To: pkrumv 
Cc: carl, osman 
Subject: TAUX reports strangely in middle of sup swap. 

At 00:05 I tried to TAUX to XRAY:8671 to look at X32's base from F33.
It kept saying "access barred".  I tried from X14, which said "no such host".
I tried from D25, and got a long delay.  Trying to build a new circuit from
the mux produced "ISIS unable to complete request".  That's when I realized
it was 3 very different symptoms of the same problem.  The SUP took over
F33's base at 00:06:29 PST and D25's base at 02:06:32 CST, at which time
the TAUX on D25 finally got through.

Moral of the story: If the network is acting crazy, try again in 30 seconds.

			/Joe
From: Carl A Baltrunas <Carl@F35.Tymnet> 
Date: Wed, 25 Jan 89 3:29:35 PST 
To: Osman Guven <Osman>, Joe Smith <JMS>, Craig Fletcher <fletcherc> 
Subject: Re: Notes from UNIX class 

To all of you...

  I asked at the desk, and they do have copies of the notes/slides used
for the class.  I do not (yet) know what they want (cost) for additional
copies.

  However, if we assune, MDFSCO is purchasing them.. (or they are free? which
I sincerely doubt)... Who wants a copy, (how many do we want?)

  I will check with Craig at lunchtime (Wednesday) and get the copies
before the class is over... presumably, I will be able to quote the price
at that time.

/Carl
PS  Let Craig know if you want a copy... /Carl
From: LMORRIS@D35.Tymnet 
Date: Thu, 26 Jan 89 12:14:02 PST 
To: CARL 
Subject: "HI! I CAN'T SEEM TO GET TO WORK"... 

HI!
I CAN'T SEEM TO GET 'RDIST' TO WORK FROM ANY OF MY DIRECTORIES. CAN U HELP?
LANDA
From: LMORRIS@D35.Tymnet 
Date: Thu, 26 Jan 89 15:52:10 PST 
To: CARL 
Subject: "HI! IT'S ME AGAIN. THERE ARE 2"... 

HI!
  IT'S ME AGAIN.  THERE ARE 2 USERNAMES THAT BELONG TO YOUR GROUP THAT ARE
INCONSISTENT IN THE ACCOUNTING DATABASE.  THEY ARE:

SPTBARK
SPUNKREV

  CID #16, COST CODE #4011, GAN 3.  THAT'S YOU GUYS.  HOW DO YOU WANT IT
FIXED.

THANKS,
LANDA
Received: from EMSTXS.Ontyme.Tymnet by D35.Tymnet; Fri, 27 Jan 89 14:02:14 PST
Received: from F74.Tymnet by EMSTUMS.Ontyme.Tymnet; Thu, 26 Jan 89 14:05:46 PST
Received: from D35.Tymnet by F74.Tymnet; Thu, 26 Jan 89 14:05:21 PST
Received: from EMSFSC.Ontyme.Tymnet by D35.Tymnet; Thu, 26 Jan 89 14:05:01 PST
Return-path: <MDCIS.D/SHUTT@EMSFSC.Ontyme.Tymnet> 
From: MDCIS.D/SHUTT@EMSFSC.Ontyme.Tymnet 
Date: 26 JAN 89 12:05:52 
To: FSC.C/BALTRUNAS@EMSFSC.Ontyme.Tymnet 
Message-id: J95256@Ontyme.Tymnet 
Subject: Request from Ted Atkinson 
RequestfromTed: 

TO:    Carl

From:  Debbie Shutt

Date:  January 26, 1989

RE:    Request from Ted

===================================================

Carl, Ted Atkinson called this afternoon.  He needs a program called
CSORT (executable) loaded to his id on system 74 (WE9915X).  They are
having problems with their phones and we can't call in.  Can you send
him a mail message?

Thanks,
Debbie
Received: from EMSTXS.Ontyme.Tymnet by D35.Tymnet; Fri, 27 Jan 89 14:02:32 PST
From: IPC.J/KRIVANEC@EMSTXS.Ontyme.Tymnet 
Date: 27 JAN 89 10:21:17 
To: TXS.C/BALTRUNAS@EMSTXS.Ontyme.Tymnet 
Message-id: A92272@Ontyme.Tymnet 
Subject: "Carl, I have validated RPMOP to"... 

Carl,

I have validated RPMOP to support any needs to the accounts that we
are responsible for. The following needs to be changed:

Give the license granted to DEBBIE to RPMOP.
Give DEBBIE license just like JKRIVANEC.

Since RPMOP is our group id to make changes for the accounts we
are responsible for, is it okay to give it my isg number? Please advise.

Please make the necessary change immediately.

Thanks, Jan.
Received: from EMSTXS.Ontyme.Tymnet by D35.Tymnet; Sat, 28 Jan 89 14:01:54 PST
Received: from F74.Tymnet by EMSTUMS.Ontyme.Tymnet; Fri, 27 Jan 89 14:37:29 PST
Received: from D35.Tymnet by F74.Tymnet; Fri, 27 Jan 89 14:05:55 PST
Received: from EMSFSC.Ontyme.Tymnet by D35.Tymnet; Fri, 27 Jan 89 14:05:30 PST
Return-path: <IPC.SRAMAIL@EMSFSC.Ontyme.Tymnet> 
From: IPC.SRAMAIL@EMSFSC.Ontyme.Tymnet 
Date: 27 JAN 89 09:52:08 
To: FSC.C/BALTRUNAS@EMSFSC.Ontyme.Tymnet 
Message-id: A92265@Ontyme.Tymnet 
Subject: TAPE 

CARL,

THE TAPE NUMBERS FOR THE 'PAS' ID'S ARE;

TRP - R566     TID - D137748

TAPE IS ASSIGNED TO SRAMOV, WITH CARL AS ACCESS USER.
Received: from EMSTXS.Ontyme.Tymnet by D35.Tymnet; Sat, 28 Jan 89 14:02:03 PST
Received: from F74.Tymnet by EMSTUMS.Ontyme.Tymnet; Fri, 27 Jan 89 14:39:53 PST
Received: from D35.Tymnet by F74.Tymnet; Fri, 27 Jan 89 14:05:59 PST
Received: from EMSFSC.Ontyme.Tymnet by D35.Tymnet; Fri, 27 Jan 89 14:05:38 PST
Return-path: <MDCIS.D/SHUTT@EMSFSC.Ontyme.Tymnet> 
From: MDCIS.D/SHUTT@EMSFSC.Ontyme.Tymnet 
Date: 27 JAN 89 13:59:40 
To: FSC.C/BALTRUNAS@EMSFSC.Ontyme.Tymnet 
Message-id: J95653@Ontyme.Tymnet 
Subject: Important KL-10 
KL-10Billing: 

To:     Carl

From:   Debbie

Date:   January 27, 1989

Re:     KL-10 Billing

++++=======================================================

Carl, after much discussion it looks as though we need to pass
the username to CPIP.  It needs to go into the field that the PPN is
presently occupying.PIP doesn't need the PPN for billing,
the MCN is important to them.  AT&T needs the username with study
type on the end for their billing.  Bob Brown is not going to use the
data that we have sent them so far because we will need to rerun it with
the username put in.  You will need to give him a call and he will discuss
with you how best to give him the new data.  Please give me a call on
Monday and let me know how long it is going to take you to modify your
program.  If you have any questions, please give me a call.  Thanks,
Debbie
Received: from F33.Tymnet by D35.Tymnet; Sun, 29 Jan 89 5:21:17 PST
Return-path: <PERPOPER@F33.Tymnet> 
Reply-to: SUBMIT 
From: F33 Job Processor 
Sender: PERPOPER@F33.Tymnet 
Date: Sun, 29 Jan 89 13:21:06 UT 
To: SYS 
Subject: Req #51424 DSK:(SYS)REDSAT.SAV Abort-Time (0) 

; Processed:  Req #51424  Running DSK:(SYS)REDSAT.SAV
; Scheduled:  22-Jan-89 23:56:43
; Actual run: 29-Jan-89 04:20:57
;
; Options:  Mail:Error Unique:Job
; Limits:  Time 60  TRUs 0
; Flags:   Run  Detach  Logout
; Status:  Abort-Time (0)  at  29-Jan-89 05:21:04

Received: from EMSTXS.Ontyme.Tymnet by D35.Tymnet; Sun, 29 Jan 89 14:01:28 PST
Received: from F74.Tymnet by EMSTUMS.Ontyme.Tymnet; Sat, 28 Jan 89 14:05:01 PST
Received: from D35.Tymnet by F74.Tymnet; Sat, 28 Jan 89 14:04:37 PST
Received: from EMSFSC.Ontyme.Tymnet by D35.Tymnet; Sat, 28 Jan 89 14:04:25 PST
Return-path: <NSC.TOMASI@EMSFSC.Ontyme.Tymnet> 
From: NSC.TOMASI@EMSFSC.Ontyme.Tymnet 
Date: 27 JAN 89 16:15:10 
To: FSC.C/BALTRUNAS@EMSFSC.Ontyme.Tymnet 
Message-id: M18472@Ontyme.Tymnet 
Subject: "MCDONNELL DOUGLAS NETWORK SYSTEMS"... 



                   MCDONNELL DOUGLAS NETWORK SYSTEMS COMPANY

                       T Y M N E T   O P E R A T I O N S

                              M E M O R A N D U M





     DATE:     January 27, 1989

     TO:       Gary Walker, Robert Klute, Debbie Mullin, Fred Canning,
               Barry O'Hara, Ken Bedell, Ron Saltgaver

     COPIES:   Al Fenn, Bob Tomasi, Carl Baltrunas, Ed Roop,
               Jan Krivanec, Vida Stafford, Cynthia Hoeke

     FROM:     Wayne Bartlett

     SUBJECT:  SETOPS Account
                                                                         



     I must countermand Jan Krivanec's 1/27/89 memo.  I am sorry about
     the confusion.

     I have been working for some time to upgrade the security features
     of SETOP.  It is finally now being implemented.  Although we have
     tried to make the upgrade as transparent as possible, part of that
     plan is to have all of Network Systems under Network Systems
     control.  Therefore, TYMNET Validations will manage SETOP functions
     for Network Systems.  You all still have your own manager functions,
     as before, but now with more flexibility.  The only added control is
     at the time a new user name is added.  That function will go through
     an audit by TYMNET Validations to insure proper information is in
     the database (of course, we are working the current "cutover
     problem" of getting all existing names and owners in the database).

     Specifically, the following (and others) are to be under MDNSC:

      GARY WALKER'S Division ---------- Gary Walker
      ACS Division ------------------- Robert Klute
      FINANCE Division ---------------- Debbie Mullin
      FINANCE Division ---------------- Fred Canning
      PAYMENTS Division --------------- Barry O'Hara
      INTERNATIONAL Division ---------- Ken Bedell
      NTD Division -------------------- Ron Saltgaver
From: Carl A Baltrunas <Carl@F35.Tymnet> 
Date: Sun, 29 Jan 89 14:33:27 PST 
To: danielsr 
Subject: OPPS on D34 

Rick,
  There is a new version of OPPS on system D34.  A new feature is to
allow any manager or (setop manager/utility) to change the password
of any individual opername on the current branch.  If the user is not
a manager, then the only one the user can change is his/her-self.

/Carl
From: Postmaster@D35.Tymnet 
Date: Sun, 29 Jan 89 15:10:02 PST 
To: Carl A Baltrunas <Carl@F35.Tymnet> 
Subject: Returned MAIL 

The following message was not delivered because:
No router table entry for "39.Q".



----------
RCPT To: <BARTLETW@B39.Tymnet> 
From: Carl A Baltrunas <Carl@F35.Tymnet> 
Date: Sun, 29 Jan 89 14:26:46 PST 
To: Monitor Group <Carl>, Osman Guven <Osman>, Joe Smith <JMS>, Craig Fletcher
	<fletcherc>, requestop@d34, Wayne D Bartlett <BARTLETW@B39.Tymnet> 
Bcc: CARL@D35.Tymnet 
Subject: SETOP :: OPPS 

Vida & Cynthia,
  As per our discussion on Friday, OPPS has now been modified to allow
users to change their OPER passwords and update the NEW setop data files.
OPPS is now ONLY on system D34.

  A possibly new feature is that a manager need not run SETOP just to
change a user's OPER password, whereas previously you were only allowed
to change your own password with OPPS.  It now validates the user by
requesting an opername and password, then allows the user to change any
opername that is on that user's particular branch.

/Carl
Received: from F33.Tymnet by D35.Tymnet; Tue, 31 Jan 89 19:53:03 PST
Return-path: <Carl@F33.Tymnet> 
From: Carl A Baltrunas <Carl> 
Date: Tue, 31 Jan 89 19:49:01 PST 
To: Monitor Group <CARL>, Osman Guven <Osman>, Joe Smith <JMS>, Craig Fletcher
	<fletcherc> 
Subject: GFD SYS 

I looked at GFD.MAC and it appears that someone put in the code to prevent
GFD to SYS: (who knows when) only one problem... it gets the SYS: ppn using
INIT and DEVPPN... why a problem?  DEVPPN skips and they stored the result
in SYSPPN at DEVPPN+1 so the later compare always checked against [0] and
never worked.

Fix: In GFD %14.7, add JFCL after DEVPPN call.  Telecopied to (OSU:*) Please
install if you notice that I've missed it.

/Carl
Received: from F33.Tymnet by D35.Tymnet; Tue, 31 Jan 89 23:44:41 PST
Return-path: <Carl@F33.Tymnet> 
From: Carl A Baltrunas <Carl> 
Date: Tue, 31 Jan 89 23:37:28 PST 
To: Monitor Group <CARL>, Osman Guven <Osman>, Joe Smith <JMS>, Craig Fletcher
	<fletcherc> 
Subject: Hotline Call XSYSF74 


Not HOTLINE.LOG FORMAT...

System: F74 FFF - could not find system structure

Ali had been called in after 9:30pm due to BADSAT/WRTSAT/etc. crashes and
after getting KL10 Halted a number of times trying to reboot the system
he decided to swap hardware from DDD to FFF.

F74 on FFF is now running full dskcln with no apparent problems (as of this
writing).


Ali beleives the problem is somewhere in the CPU...SA10 path since FFF is
not having any problems.  Anyway, since it it presumed to be HARDWARE, we
are off the case until further notice.

We were called prior to Ali's notification that F74 was running dskcln. I
was talking to Bonnie Terry when operations was notified of this information.

/Carl
...more later if necessary...
Received: from F33.Tymnet by D35.Tymnet; Wed, 1 Feb 89 19:07:17 PST
Return-path: <Carl@F33.Tymnet> 
From: Carl A Baltrunas <Carl> 
Date: Wed, 1 Feb 89 19:02:37 PST 
To: Monitor Group <CARL>, Osman Guven <Osman>, Joe Smith <JMS>, Craig Fletcher
	<fletcherc> 
Subject: re: SETE %14 

As we had thought, SETE both in the monitor and the program had been
updated.  However, (SYS)SETE.SAV was version %11.  I suspect that the
change was made (2-Dec-87) and never put on SYS because we hadn't put
up the new monitor anywhere except on our test system(s).  Then it was
overlooked.

I will telecopy it everwhere (OSU:*)SETE.SAV, although the source is (MPL).
This is a monitor utility and belongs in (OSU) due to it's nature.

/Carl
Received: from EMSTXS.Ontyme.Tymnet by D35.Tymnet; Fri, 3 Feb 89 14:01:52 PST
Received: from F74.Tymnet by EMSTUMS.Ontyme.Tymnet; Thu, 2 Feb 89 14:04:42 PST
Received: from D35.Tymnet by F74.Tymnet; Thu, 2 Feb 89 14:04:21 PST
Received: from EMSFSC.Ontyme.Tymnet by D35.Tymnet; Thu, 2 Feb 89 14:04:01 PST
Return-path: <FSC.K/OKEY@EMSFSC.Ontyme.Tymnet> 
From: FSC.K/OKEY@EMSFSC.Ontyme.Tymnet 
Date: 02 FEB 89 10:09:47 
To: FSC.C/BALTRUNAS@EMSFSC.Ontyme.Tymnet 
Message-id: P15831@Ontyme.Tymnet 
Subject: STANDBY FOR FEBRUARY 1989 
StandbyforFebruary1989: 

              MCDONNELL DOUGLAS FIELD SERVICE COMPANY
 
 
                            MEMORANDUM
 
 
 
TO:           Distribution

FROM:         Craig Fletcher

DATE:         28 January 1989

SUBJECT:      Standby for February 1989

_________________________________________________________________

Here is the Software Standby Schedule for February:

   Week Beginning:   01/27/89           C. Baltrunas
                     02/06/89           O. Guven
                     02/13/89           J. Smith
                     02/20/89           C. Baltrunas
                     02/27/89           O. Guven

Regards, Craig

cc: C. Baltrunas, O. Guven, J. Smith, J. Shields, R. Rawlins,
From: Carl A Baltrunas <Carl@F35.Tymnet> 
Date: Sun, 5 Feb 89 22:37:50 PST 
To: Monitor Group <Carl>, Osman Guven <Osman>, Joe Smith <JMS>, Craig Fletcher
	<fletcherc> 
Subject: Group name? 

As you may have noticed in my previous posting, I've invented a new name
for our group.. in between Host Support and Network Host support.. but one
that says what we do.. Not just SUPPORT, we are software engineers, so we
should publish that fact, make the company realize that we think, design,
create, (in effect: engineer) and provide support, hand-holding, etc....

Please, no flames... I don't remember our exact "real" name anymore, I mean
I use it so often... sigh!


/Carl;
Received: from F74.Tymnet.COM by D35.Tymnet; Sun, 5 Feb 89 22:42:55 PST
Return-path: <Postmaster@F74.Tymnet> 
From: Postmaster@F74.Tymnet 
Date: Sun, 5 Feb 89 23:23:19 PST 
To: <Carl@F35.Tymnet> 
Subject: Returned MAIL 

The following message was not delivered because:
The request was rejected by EMSTXS.Ontyme.Tymnet
The response was:
:send NSC.W/BARTLETT NSC.V/Stafford NSC.C/Hoeke IPC.E/Roop IPC.D/Mullen FSC.C/Fletcher
SUBJ: 
NONEXISTENT RECIPIENT
IPC.D/MULLEN
MSG # A94914 SENT AT 05 FEB 89 22:37:57  


----------
RCPT To: <IPC.D/MULLEN.@EMSTXS.Ontyme.Tymnet> 
Received: from F74.Tymnet by EMSTXS.Ontyme.Tymnet; Sun, 5 Feb 89 23:20:34 PST
Received: from D34.Tymnet.COM by F74.Tymnet; Sun, 5 Feb 89 23:20:14 PST
Return-path: <Carl@F35.Tymnet> 
From: Carl A Baltrunas <Carl@F35.Tymnet> 
Date: Mon, 6 Feb 89 0:01:11 CST 
To: Wayne D Bartlett <NSC.W/BARTLETT@Ontyme.Tymnet>, Vida Stafford
	<NSC.V/Stafford@Ontyme.Tymnet>, Cynthia Hoeke
	<NSC.C/Hoeke@Ontyme.Tymnet>, Ed Roop <IPC.E/Roop@Ontyme.Tymnet>, Debbie
	Mullen <IPC.D/Mullen@Ontyme.Tymnet>, Monitor Group <Carl>, Osman Guven
	<Osman>, Joe Smith <JMS>, Craig Fletcher <fletcherc> 
Subject: SETOP cutover and changes 

This is to inform you that the newest release of SETOP has been installed
on system D34. The changes include:

 o  Opernames with no employee number are written to the password file
    as before, except their license field is 0.  If they try to set their
    license they receive the message "Did not set OP".  In effect they
    are disabled until their ISG/Employee numbers are entered.

 o  The DATES and NODATES commands have been added.  These commands control
    the printing of the password change date information as in the old
    version of SETOP.

 o  SM capability has a new meaning.  SM (Setop Manager) allows the user
    to create and delete oper names and otherwise manage the entire tree.

 o  BM capability (Branch Manager) allows the user to create and delete
    oper names and otherwise manage the current branch including all of
    its sub-branches and leaves.

 o  The IMITATE command now requires SU (Setop Utility) capability in
    order to properly record the "on behalf of" license grant.

 o  SU capability has been removed from all oper names other than ROOT
    and that of the SETOP maintainers.  Albeit this will make it slightly
    more difficult to grant license on behalf of a manager, it is felt
    that anyone that needs to grant license, understand how to do it and
    manage that responsibility themselves.  VALIDATIONS WILL NOT grant
    the actual license to the individual oper names, and therefore does
    NOT need the ability to grant license "on behalf" of another user.


/Carl Baltrunas, MDFSCO: Network Host Software Engineering group
From: Carl A Baltrunas <Carl@F35.Tymnet> 
Date: Sun, 5 Feb 89 22:44:34 PST 
To: ipc.d/burns@ontyme.tymnet 
Subject: Mail bounce 

Debbie,
  I sent a note about SETOP to a group a people that were on the
memo's sent back and forth between Ed and Wayne and used their return
address and apparently they had your name spelled wrong... so, please
get a copy of the message from Ed Roop, or let me know to re-send it
to you.

  /Thanks.   - Carl
Received: from F74.Tymnet.COM by D35.Tymnet; Sun, 5 Feb 89 22:56:02 PST
Return-path: <Postmaster@F74.Tymnet> 
From: Postmaster@F74.Tymnet 
Date: Sun, 5 Feb 89 23:35:04 PST 
To: <Carl@F35.Tymnet> 
Subject: Returned MAIL 

The following message was not delivered because:
The request was rejected by EMSTXS.Ontyme.Tymnet
The response was:
:send ipc.d/burns
SUBJ: 
NONEXISTENT RECIPIENT
IPC.D/BURNS
MESSAGE NOT SENT


----------
RCPT To: <IPC.D/BURNS.@EMSTXS.Ontyme.Tymnet> 
Received: from F74.Tymnet by EMSTXS.Ontyme.Tymnet; Sun, 5 Feb 89 23:32:39 PST
Received: from D35.Tymnet.COM by F74.Tymnet; Sun, 5 Feb 89 23:32:19 PST
Return-path: <Carl@F35.Tymnet> 
From: Carl A Baltrunas <Carl@F35.Tymnet> 
Date: Sun, 5 Feb 89 22:44:34 PST 
To: ipc.d/burns@ontyme.tymnet 
Subject: Mail bounce 

Debbie,
  I sent a note about SETOP to a group a people that were on the
memo's sent back and forth between Ed and Wayne and used their return
address and apparently they had your name spelled wrong... so, please
get a copy of the message from Ed Roop, or let me know to re-send it
to you.

  /Thanks.   - Carl
Received: from EMSTXS.Ontyme.Tymnet by D35.Tymnet; Mon, 6 Feb 89 14:01:26 PST
From: SYSTEM.ONTYME@EMSTXS.Ontyme.Tymnet 
Date: 05 FEB 89 23:00:32 
To: <Carl@F35.Tymnet> 
Message-id: A94920@Ontyme.Tymnet 
Subject: UNDELIVERABLE MESSAGE - INVALID RECIPIENTS 

Message #A94914 was not delivered to the following recipient(s):

        NSC.W/BARTLETT.

These recipients do not exist.
Please check the spelling of the recipient(s) listed above.

(undelivered message follows)
------------------------------------------------------------------------
Received: from F74.Tymnet by EMSTXS.Ontyme.Tymnet; Sun, 5 Feb 89 23:20:34 PST
Received: from D34.Tymnet.COM by F74.Tymnet; Sun, 5 Feb 89 23:20:14 PST
Return-path: <Carl@F35.Tymnet> 
From: Carl A Baltrunas <Carl@F35.Tymnet> 
Date: Mon, 6 Feb 89 0:01:11 CST 
To: Wayne D Bartlett <NSC.W/BARTLETT@Ontyme.Tymnet>, Vida Stafford
        <NSC.V/Stafford@Ontyme.Tymnet>, Cynthia Hoeke
        <NSC.C/Hoeke@Ontyme.Tymnet>, Ed Roop <IPC.E/Roop@Ontyme.Tymnet>, Debbie
        Mullen <IPC.D/Mullen@Ontyme.Tymnet>, Monitor Group <Carl>, Osman Guven
        <Osman>, Joe Smith <JMS>, Craig Fletcher <fletcherc> 
Subject: SETOP cutover and changes 

This is to inform you that the newest release of SETOP has been installed
on system D34. The changes include:

 o  Opernames with no employee number are written to the password file
    as before, except their license field is 0.  If they try to set their
    license they receive the message "Did not set OP".  In effect they
    are disabled until their ISG/Employee numbers are entered.

 o  The DATES and NODATES commands have been added.  These commands control
    the printing of the password change date information as in the old
    version of SETOP.

 o  SM capability has a new meaning.  SM (Setop Manager) allows the user
    to create and delete oper names and otherwise manage the entire tree.

 o  BM capability (Branch Manager) allows the user to create and delete
    oper names and otherwise manage the current branch including all of
    its sub-branches and leaves.

 o  The IMITATE command now requires SU (Setop Utility) capability in
    order to properly record the "on behalf of" license grant.

 o  SU capability has been removed from all oper names other than ROOT
    and that of the SETOP maintainers.  Albeit this will make it slightly
    more difficult to grant license on behalf of a manager, it is felt
    that anyone that needs to grant license, understand how to do it and
    manage that responsibility themselves.  VALIDATIONS WILL NOT grant
    the actual license to the individual oper names, and therefore does
    NOT need the ability to grant license "on behalf" of another user.


/Carl Baltrunas, MDFSCO: Network Host Software Engineering group
Received: from F74.Tymnet.COM by D35.Tymnet; Mon, 6 Feb 89 23:16:05 PST
Return-path: <JMS@F74.Tymnet.COM> 
From: JMS@F74.Tymnet.COM 
Date: Mon, 6 Feb 89 23:14:48 PST 
To: carl 
Subject: "What causes POSSIBLE COMPILED"... 

What causes POSSIBLE COMPILED CODE-RUNTIME INCOMPATIBILITY?
I ran into it trying to rebuild MAILER.SAV from (TUMS)MAILER.CMD.
From: Carl A Baltrunas <Carl@F35.Tymnet> 
Date: Tue, 7 Feb 89 3:58:49 PST 
To: Joe Smith <JMS> 
Subject: Re: RUNTIME IN-COMPATIBILITY 

Well... it's like this, FTSYS:SAIL and SYS:SAIL produce identical code at
the moment, however it has NOT always been this way.  There is ONE major
factor that separates these two released versions of SAIL.  They have a
different compiler/runtime version number assembled into them.

Thus, when you link code that has been compiled with one or the other
together, there is this little INIT procedure that gets called at runtime
which makes sure we're all using the same runtimes by checking what version
each module was compiled with.

Whenever it finds one that doesn't match, it complains... unfortunately, it
was never made to understand to tell the poor user what the version numbers
or what modules are at fault.

In NDT, Scott had a program which printed out these version numbers, but it
would take some work to locate it and fit it into TUMS.

To complicate matters, any "require" files that reference (SAILIB), have
an other set of idiosyncracies... they have compile-time switches that check
the compiler version and they attempt (and are 95% right) to load the library
.REL file that matches the right compiler versions.  That's why you'll find
APPEND.REL and APEND.REL, etc... See (SAILIB)SAIL.DEF for some gore... esp.
see the section on get!module or get!library...

Either one or more of the library versions do not match.  Check your RPG.INI
to see what version of SAIL you are using to compile with... Bill may have
used a different version.  Usually (FTSYS) vs (SYS) is the biggie.

/Carl

From: Carl A Baltrunas <Carl@F35.Tymnet> 
Date: Tue, 7 Feb 89 4:09:38 PST 
To: Paul Krumviede <PKrumv@F33.Tymnet> 
Subject: Re: Setting LICENSE of F33 

Um.. my fault actually, F33 is my test host for the new SETOP program and
I turned the switch to only write validated OPERnames to the password file.

My fault, because the database I was using was a 2-week old base that didn't
have any (read *ANY*) users validated properly with their ISC employee numbers
so, although everything was written correctly on D34, when I exited my test
copy on F33, it clobbered the real file with stale data.

You had an opername that had 0 license.  Since you said O... without asking
for explicit licenses, it said, oh.. you want, let me see.. nothing, OK! and
set nothing(!) so it didn't complain, 'cuz your password and all was alright.

The other problem is that it would fix itself when the password-file daemon
runs, but that happens to be every 150 minutes (read 2.5 hours).  I got a
call from operations and I fixed it!

FYI... the newest latest greatest version is this hour now running on D34.
       It is a little kinder about some things, and now enforced the TYMNET
       password standard of nothing trite, nothing short, nothing without
       an embedded non-alpha, etc...                  (up 2, "d" should be "s")

/Carl
Received: from EMSTXS.Ontyme.Tymnet by D35.Tymnet; Tue, 7 Feb 89 14:02:00 PST
Received: from F74.Tymnet.COM by EMSTUMS.Ontyme.Tymnet; Mon, 6 Feb 89 21:47:10
	PST
Received: from D35.Tymnet.COM by F74.Tymnet.COM; Mon, 6 Feb 89 14:31:48 PST
Received: from EMSFSC.Ontyme.Tymnet by D35.Tymnet; Mon, 6 Feb 89 14:03:27 PST
Return-path: <MDCIS.D/SHUTT@EMSFSC.Ontyme.Tymnet> 
From: MDCIS.D/SHUTT@EMSFSC.Ontyme.Tymnet 
Date: 06 FEB 89 12:00:48 
To: FSC.C/BALTRUNAS@EMSFSC.Ontyme.Tymnet 
Message-id: J98394@Ontyme.Tymnet 
Subject: KL-10 Conference Call 
KL-10BillingCall: 

M E M O

To:   Carl

From: Debbie

Date: February 6, 1989

RE:   KL-10 Billing Call

==============================================================

Carl, Will you be available for a conference call with Jim O'Connell,
Bob Brown, Bob Tucker, and myself on Tuesday afternoon?  Jim wants to 
discuss some outstanding issues with us.  Please send me an ONTYME and
let me know when you are available.  Thanks,

Debbie
Received: from F74.Tymnet.COM by D35.Tymnet.COM; Wed, 8 Feb 89 11:14:19 PST
Return-path: <DANIELSR@F74.Tymnet.COM> 
From: DANIELSR@F74.Tymnet.COM 
Date: Wed, 8 Feb 89 11:13:18 PST 
To: CARL 
Subject: "Carl; I've misplaced my copy of"... 


Carl;

I've misplaced my copy of your document SETOP.GED and I forgot where it
is at.  Could you give me this info again.

Thanks 
rick
Received: from F33.Tymnet.COM by D35.Tymnet.COM; Wed, 8 Feb 89 12:39:13 PST
Return-path: <PKrumv@F33.Tymnet> 
From: Paul Krumviede <PKrumv@F33.Tymnet> 
Date: Wed, 8 Feb 89 12:35:53 PST 
To: carl@d35 
Subject: license? 

Carl,
  Ron and I were playing with SETOP and had a few questions that don't seem
to have obvious answers.
  What is BM capability?  Is it anything like SM?
  How does someone get LG capability?  People like Ed Mooring (license name
ETM) have traditionally run much of the oper stuff for us and QA, but he
doesn't have LG.  Does he even need it to continue to manage existing names
and their licenses?

paul
Received: from F74.Tymnet.COM by D35.Tymnet.COM; Wed, 8 Feb 89 13:51:56 PST
Return-path: <JMS@F74.Tymnet.COM> 
From: Joe Smith <JMS@F74.Tymnet.COM> 
Date: Wed, 8 Feb 89 13:47:44 PST 
To: <wrs@buffalo.Tymnet.COM> 
Cc: carl 
Subject: Re: 39 and TUMS 
In-reply-to: <8902082144.AA15564@buffalo.Tymnet.COM> of Wed, 8 Feb 89 13:44:58
	PST

I had operations "STORE G3" on B39 and restore on X32 with "MODE OLD NEW" so
that system 32 should have the most recent files.  I'm sure F74 is not up
to date.

I don't know if B39's packs are still mounted; you'd have to ask the Fremont
Data Center.  If not, you could have them restore (SAILIB) from B39's final
all-files tape to some other directory on X32 or F74.

		/Joe
Received: from F74.Tymnet.COM by D35.Tymnet.COM; Wed, 8 Feb 89 13:52:18 PST
Received: from tymix.Tymnet.COM by F74.Tymnet.COM; Wed, 8 Feb 89 13:46:01 PST
Received: from buffalo.Tymnet.COM by tymix.Tymnet.COM (5.61/1.34) id AA03783;
	Wed, 8 Feb 89 13:45:05 -0800
Received: by buffalo.Tymnet.COM (3.2/SMI-3.2) id AA15564; Wed, 8 Feb 89
	13:44:58 PST
Return-path: <JMS@F74.Tymnet.COM> 
From: wrs@buffalo.Tymnet.COM (Bill Soley) 
Date: Wed, 8 Feb 89 13:44:58 PST 
To: jms@f74.Tymnet.COM 
Message-id: <8902082144.AA15564@buffalo.Tymnet.COM> 
Subject: 39 and TUMS 
Resent-from: Joe Smith <JMS@F74.Tymnet.COM> 
Resent-date: Wed, 8 Feb 89 13:52:07 PST 
Resent-to: carl 

1. is 39 still up somewhere (i.e. 39's packs)?
2. any idea on problems with PEAK, still getting complaints.  Error code
   says file not found (SYS)PEAK from FRMRUN.  I think maybe an old version
   of FRMRUN library on 74 that causes problems?  
-Bill
Received: from D34.Tymnet.COM by D35.Tymnet.COM; Thu, 9 Feb 89 5:58:03 PST
Return-path: <DANIELSR@D34.Tymnet.COM> 
From: DANIELSR@D34.Tymnet.COM 
Date: Thu, 9 Feb 89 5:55:47 PST 
To: CARL 
Subject: "Carl; Was making changes to Opername"... 


Carl;

Was making changes to Opername PALS and after making some changes

I received the OPRTXT Text pointer mangled: (). message again.

This is getting to be old stuff everytime changes are requiered.


Thanks Rick
Received: from D34.Tymnet.COM by D35.Tymnet.COM; Thu, 9 Feb 89 6:07:59 PST
Return-path: <DANIELSR@D34.Tymnet.COM> 
From: DANIELSR@D34.Tymnet.COM 
Date: Thu, 9 Feb 89 6:07:17 PST 
To: CARL 
Subject: "Went back and used APPEND and"... 


Went back and used APPEND and it seems to have cleared up the problem.

Thansk Rick
Received: from EMSTXS.Ontyme.Tymnet by D35.Tymnet.COM; Thu, 9 Feb 89 14:01:43
	PST
Received: from F74.Tymnet.COM by EMSTUMS.Ontyme.Tymnet; Wed, 8 Feb 89 14:05:20
	PST
Received: from D35.Tymnet.COM by F74.Tymnet.COM; Wed, 8 Feb 89 14:04:54 PST
Received: from EMSFSC.Ontyme.Tymnet by D35.Tymnet.COM; Wed, 8 Feb 89 14:04:37
	PST
Return-path: <MDCIS.D/SHUTT@EMSFSC.Ontyme.Tymnet> 
From: MDCIS.D/SHUTT@EMSFSC.Ontyme.Tymnet 
Date: 08 FEB 89 06:45:49 
To: FSC.C/BALTRUNAS@EMSFSC.Ontyme.Tymnet 
Message-id: J99036@Ontyme.Tymnet 
Subject: California Trip 
CaliforniaTrip: 

Memo


To:    Carl

From:  Debbie

Date:  February 8, 1989

Re:    California Trip

==============================================================

Carl, is it okay with you if we postpone my trip to the following week?
That would be March 1 and 2.  I need to be here in St. Louis to make sure
all accounting gets in before the cycle ends on the 24th.  Let me know.
Thanks,
Debbie
Received: from F33.Tymnet.COM by D35.Tymnet.COM; Thu, 9 Feb 89 16:26:34 PST
Return-path: <Postmaster@F33.Tymnet> 
From: Postmaster@F33.Tymnet 
Date: Thu, 9 Feb 89 16:13:55 PST 
To: CARL@F33.Tymnet 
Subject: Returned MAIL 

The following message was not delivered because:
User has not read mail in 30 days: REQUESTOP
Last logout: 1 Jan 64


----------
RCPT To: <REQUESTOP> 
From: CARL@F33.Tymnet 
Date: Wed, 11 Jan 89 15:38:02 PST 
To: REQUESTOP 
Subject: SETOP User Request at 11-Jan-89 23:38:01 

Oper:  DEBBIE       manager: SRAVAL      
Password hash: 504060551751
Privileges:    MG LG
Mktg District: 0
Name:  d. burns
ISC Id#222222 center: St.Louis
Phone: 4444444; Mailstop: 333
User:  burns1
Mail:  
Supv:  roop
Dept:  ipc 256
Why:   'cause


Received: from F74.Tymnet.COM by D35.Tymnet.COM; Thu, 9 Feb 89 19:19:52 PST
Return-path: <JMS@F74.Tymnet.COM> 
From: Joe Smith <JMS@F74.Tymnet.COM> 
Date: Thu, 9 Feb 89 19:19:05 PST 
To: Monitor Group <JMS>, Carl, Osman 
Cc: FletcherC 
Subject: NODE 7004 UPGRADE 

(begin forwarded message)

Received: from D35.Tymnet.COM by F74.Tymnet.COM; Thu, 9 Feb 89 14:05:26 PST
Received: from EMSFSC.Ontyme.Tymnet by D35.Tymnet.COM; Thu, 9 Feb 89 14:04:11
	PST
Return-path: <FSC.L/FRANSCINI@EMSFSC.Ontyme.Tymnet> 
From: FSC.L/FRANSCINI@EMSFSC.Ontyme.Tymnet 
Date: 09 FEB 89 05:25:27 
To: FSC.JM/SMITH@EMSFSC.Ontyme.Tymnet 
Message-id: P17367@Ontyme.Tymnet 
Subject: NODE 7004 UPGRADE 

GENTLEMEN,

    I WANTED TO FIND OUT IF THE TYMCOM-X GROUP STILL DOES THE
PDP-10 BASE CODE GENERATION. THERE IS A PROJECT #47582 TO REMOVE A 9.6
HARDWIRE AND INSTALL A MEMORY SHUFFLER LINK FROM NODE 4261 TO EBUS
NODE 7004. THE PROJECT LISTS THE BOUND FILE IN THE TYM5 DIRECTORY IS TO
BE LOADED INTO 7004 BUT I NOTICED THE NW7004.BND FILE IS ONLY 63 PAGES
LONG AS COMPARED TO THE TYPICAL 69 PAGES FOR EBUS NODES. I WOULD APPRECIATE
YOUR RESPONSE ON THIS WHEN YOU GET A CHANCE. THE PROJECT IS TENTATIVELY
SCHEDULED FOR WEDNESDAY, FEBRUARY 15TH AND I WOULD LIKE TO BE SURE
THE CODE FOR 7004 IS GOING TO WORK TO BE SURE HOST 31 ISN'T DOWN ANY
LONGER THAN NECESSARY.

    SO TO SUMMARIZE, NODE 7004 NEEDS THE CODE TO LOOK FOR MS LINKS FROM
SWITCHERS ND4261 AND ND5405. THE HOST INTERFACE SLOT SHOULD NOT
NEED TO BE CHANGED BUT I'LL LEAVE IT UP TO SOFTWARE SUPPORT TO DECIDE HOW

THE CODE SHOULD BE SET UP.

THANKS IN ADVANCE FOR YOUR COOPERATION
LUCIEN FRANSCINI (ONTYME FSC.L/FRANSCINI)
DALLAS DISTRICT #2

   _                         _____
 _//                          /  '
 /    . . _. o _  __       ,-/-, __  __. __   _   _. o __   o
/___ (_/_(__(_(<_/) )_    (_/   / (_(_(_/) )_/_)_(__(_/) )_(_




(end forwarded message)


From: Joe Smith <JMS@F74.Tymnet.COM> 
Date: Thu, 9 Feb 89 19:16:53 PST 
To: <FSC.L/FRANSCINI@EMSFSC.Ontyme.Tymnet> 
Subject: Re: NODE 7004 UPGRADE 
In-reply-to: P17367@Ontyme.Tymnet of 09 FEB 89 05:25:27

Yes, we support the EBUS base code.
I updated ND7004.TYM to have 2 SIO lines and 0 SYNC lines.
The new BND file is (TYM5)NW7004.BND on F33 and D54.

		/Joe

Received: from D34.Tymnet.COM by D35.Tymnet.COM; Fri, 10 Feb 89 2:28:04 PST
Return-path: <Carl@F35.Tymnet> 
From: Carl A Baltrunas <Carl@F35.Tymnet> 
Date: Fri, 10 Feb 89 4:26:32 CST 
To: William R Soley <WRS@Tymix> 
Subject: LPR 

Bill,
  Does LPR on the PDP-10s accept any switches?  if so, what switches?

I typed "LPR ?" but it of course tried to spool file "?" which isn't there.

/Carl
Received: from D34.Tymnet.COM by D35.Tymnet.COM; Fri, 10 Feb 89 2:28:56 PST
Return-path: <Carl@F35.Tymnet> 
From: Carl A Baltrunas <Carl@F35.Tymnet> 
Date: Fri, 10 Feb 89 4:28:03 CST 
To: William R Soley <WRS@Tymix> 
Subject: LPR 

...mostly, I'd like to change it from landscape to portrait and possibly
indent so I can 3-hole punch the listing.

/Carl
Received: from F74.Tymnet.COM by D35.Tymnet.COM; Fri, 10 Feb 89 11:31:41 PST
Received: from tymix.Tymnet.COM by F74.Tymnet.COM; Fri, 10 Feb 89 11:31:27 PST
Received: from buffalo.Tymnet.COM by tymix.Tymnet.COM (5.61/1.34) id AA20787;
	Fri, 10 Feb 89 10:35:52 -0800
Received: by buffalo.Tymnet.COM (3.2/SMI-3.2) id AA16783; Fri, 10 Feb 89
	10:35:49 PST
Return-path: <wrs@buffalo.Tymnet.COM> 
From: wrs@buffalo.Tymnet.COM (Bill Soley) 
Date: Fri, 10 Feb 89 10:35:49 PST 
To: Carl@F35.Tymnet.COM 
Message-id: <8902101835.AA16783@buffalo.Tymnet.COM> 
Subject: Re: LPR 

.lpr
lpr - off line print to net-lpr laser printer

synopsis:
  lpr -options file1 file2 ... filen
  r(xexec)lpr; -options file1 file2 ... filen

options:
  -p    print with page headings
  -#nn  print nn copies
  -op   orientation: portrait
  -i    indent text 8 columns
  -i nn indent text nn columns
  -t    trace circuit traffic

End of SAIL execution
.
l@)”